$(document).ready(function(){
$(".secundario").on("click",function(){
    $("#principal").css("background-color",$(this).css("background-color"));
})
$(".secundario").on("mouseenter",function(evento){
    $("#mensaje").css({
        "background-color":"turquoise",
         "color":"black",
         "width":150,
         "heigth":50,
         "text-align":"center",
         "position":"absolute",
         "visibility":"visible",
         "border-radius":5,
         "left":evento.pageX,
         "top":evento.pageY
          })
  $("#mensaje").text($(this).data("nombre"));
})
$(".secundario").on("mouseleave",function(){
    $("#mensaje").css({
         "visibility":"hidden"
          })

})
})